# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d398698b7805be1671e13d72a80ab4c965dddcd36134817cea0b709af1f7c3f502f280dc48f25ee4228ffee5318d9191b9d9714f98ebfd8db9d724107523561

test:
  secret_key_base: 63cb0433d3582299ea0a2ce2c679b89fb51dd7646b122f725f85686026129a5fd68f0ad5527ac1a3fe98ffdfadd617447be7bfb956925dd0906a55e637500c93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
